### ISSUE TITLE
Custom Team Numbers Additions

### ISSUE THREAD

**Issue by John-Dean** [typedeck0/Know-thy-enemy#10]
Could you potentially expand the team selection so we can add our own boxes:
![image](https://github.com/typedeck0/Know-thy-enemy/assets/13804523/251bbe69-4fa0-446e-985d-e9967f482b64)

So we can add for example a new row:
0001 | Purple team

There are a few instances (Armistice Bastion, Guild hall) where they are >3 teams or teams with weird numbers, would be great if they could be expanded this way.

Maybe also if it supported CSV, like
0001, 0002, 0003 | Red team

Thanks,
John

**Comment by typedeck0** [comment]
How many extra teams do you think would fulfill the case requiring the most teams? besides red green and blue

**Comment by John-Dean** [comment]
I think there are 6 potential teams: blue, green, red, invuln, ffa, and
neutral (no team)

I haven't checked eotm arena/spectator mode there yet either.

John

**Comment by typedeck0** [comment]
I didnt do csvs but i added three custom teams, the teams can have the same or different name/ids
