### ISSUE TITLE
Creating a new history for each new enemy

### ISSUE THREAD

**Issue by typedeck0** [typedeck0/Know-thy-enemy#11]
only logs one person per history, I am working on it.

**Comment by iruixos** [comment]
I was just going to report this :) thank you!

**Comment by typedeck0** [comment]
inst_id's no longer populated in combat events revert to just using agent ids, fixed for now. [c7b6625](https://github.com/typedeck0/Know-thy-enemy/commit/c7b66257d2f73a22b381b1b1bc52d95247cb6064)
