### ISSUE TITLE
Arcdps changes

### ISSUE THREAD

**Issue by John-Dean** [typedeck0/Know-thy-enemy#13]
Apologies, can you comment as to what changed in the arcdps api (I assume?) - the arc dev is horrific at documenting things

**Comment by typedeck0** [comment]
instance ids were removed from combat events in WvW. They either never get set or are replaced with 0xFFFF before being sent to the callback. The ag->id might be unique for short fights but as the fight continues longer than a few seconds the agents start repeating old ids
