### ISSUE TITLE
No info showing

### ISSUE THREAD

**Issue by michaelstephens** [typedeck0/Know-thy-enemy#15]
👋 as of late post patch, it looks like something isn't working right. No enemies are registering for any fights:
![image](https://github.com/typedeck0/Know-thy-enemy/assets/1581475/ed270acb-b758-4ca0-b639-7f9dd132b9d7)
vs what plenbotlog uploads:
![image](https://github.com/typedeck0/Know-thy-enemy/assets/1581475/a399ee47-2a92-4a17-82c4-a4570a2faabc)

Settings:
![image](https://github.com/typedeck0/Know-thy-enemy/assets/1581475/5c29b327-d7a4-44e7-837d-b9e4390f33ef)

I couldn't find any logs, but if you point me in the right direction I'm happy to grab them and share

**Comment by typedeck0** [comment]
It is known, the arcdps dev keeps making un-documented changes to how agent ids are handled and presented in the API, unfortunately wont be able to work on this until the weekend

**Comment by michaelstephens** [comment]
> It is known, the arcdps dev keeps making un-documented changes to how agent ids are handled and presented in the API, unfortunately wont be able to work on this until the weekend

I figured but didn't see any issues open, so for nothing else but some posterity then 😂

**Comment by typedeck0** [comment]
fixed release 4.4, for now
