### ISSUE TITLE
Not Work after last patch

### ISSUE THREAD

**Issue by ducadiebonhawke** [typedeck0/Know-thy-enemy#16]
Hello , after last patch the add on start to work just show No teams , No Hits .
See image.
The version installed it is the last one.
Thanks for your help

<img width="627" alt="Immagine 2023-07-21 235411" src="https://github.com/typedeck0/Know-thy-enemy/assets/134237499/db4fd5e3-37f0-4d59-a1df-53cf81d3faa6">

**Comment by typedeck0** [comment]
#15
