### ISSUE TITLE
Instant game client crash with today's ArcDPS version

### ISSUE THREAD

**Issue by djdookie** [typedeck0/Know-thy-enemy#17]
After updating ArcDPS to version 20230823-025443, the gameclient instantly crashes if the current version of know-thy-enemy is used (https://github.com/typedeck0/Know-thy-enemy/releases/tag/4.5).

**Comment by TheWhiteWolves** [comment]
suspect its to do with this

>  aug.22.2023: removed d3d9 support code.

**Comment by typedeck0** [comment]
Yeah, I'll have to recalc some internal code. Will update later today, eastern std time.

**Comment by typedeck0** [comment]
fixed in 4.6.*
