### ISSUE TITLE
Know-thy-enemy Team display does not work correctly

### ISSUE THREAD

**Issue by master1782** [typedeck0/Know-thy-enemy#18]
Hello,
I downloaded the latest version and noticed that the WvW team colors are not displayed correctly or only partially.
If it is not the plugin what do I have to set so that works properly.
![arcdps-kte](https://github.com/typedeck0/Know-thy-enemy/assets/42435596/3e6b2e81-619d-4a14-9648-9dc603522665)

**Comment by typedeck0** [comment]
go in the arcdps settings (alt+shift+t) go to the extension tab -> then to KTE -> there you can change the team number for green to 2752.

**Comment by master1782** [comment]
Where can I get the team number?
If I change the team number do I have to change it every time I change the account?

**Comment by typedeck0** [comment]
![image](https://github.com/typedeck0/Know-thy-enemy/assets/113395677/94faa04f-6334-44a3-83a4-2ba084eba325)
No, when it is set itll persist.
