### ISSUE TITLE
Data isn't showing up

### ISSUE THREAD

**Issue by Dagda47** [typedeck0/Know-thy-enemy#19]
I'm using the following arc addons:

![image](https://github.com/typedeck0/Know-thy-enemy/assets/24296416/67815fa2-3e79-4e8b-9ec6-bf1adceb6eff)

But i can't seem to get Know thy enemy working again. It is broken for a while now.
I can see the window with title bar and right click to change settings is working fine too. But while and after fighting no data shows up like it used to. Here is an example:

![image](https://github.com/typedeck0/Know-thy-enemy/assets/24296416/f63d3335-a16f-41e5-a15c-e891e47b6fbf)

I'm not really sure what the problem is. I checked settings and deleted the settings file. But nothing really changes.

I could use some help. :(

**Comment by Dagda47** [comment]
Nevermind. I must have made the window very small for some reason and the window size didn't reset after deletion of the settings file.

With my arc-modifier keys i could enlargen the window and i can see my enemies again.

**Comment by typedeck0** [comment]
yeah its a bug with arcdps, happens to the healing addon i use all the time
