### ISSUE TITLE
Visability based on arcdps layout

### ISSUE THREAD

**Issue by bbck** [typedeck0/Know-thy-enemy#2]
arcdps has different window layouts for PvE and WvW. It would be convenient if the plugin window had the ability to be only shown in the WvW layout.

**Comment by typedeck0** [comment]
517808f Implemented in 1.9. Arcdps doesnt provide a realtime way to retrieve this information, as such I had to use another method provided b GW2 to implement this, its not instant but should enable/disable the addon based on map.

Cheers
