### ISSUE TITLE
Source changes not on Github

### ISSUE THREAD

**Issue by SickElmo-GH** [typedeck0/Know-thy-enemy#20]
I noticed that none of the release updates got the source code of the changes pushed to Git.
On the release tag it's always the "old" source code without the recent changes.
Would be great to see what was changed recently in the code, since the repo code wouldn't work right away.

**Comment by typedeck0** [comment]
ive been keeping it closed due to some sensitivity reasons, but im just going to release the current code

**Comment by typedeck0** [comment]
to tack on to this, i removed portions related to actual parsing out the data but kept the structure
