### ISSUE TITLE
11/1/2024 - Extension no longer launching in WvW

### ISSUE THREAD

**Issue by freakofnatur-git** [typedeck0/Know-thy-enemy#23]
Tested 11/1 WvW Rush Event seemed to have broken the extension with the update after also updating arcdps.

Reset position/Reset settings/Untick/Tick Extension Option tested, no response from extension.

**Comment by typedeck0** [comment]
Will require me to write an update, hopefully this weekend

**Comment by VirtualReign** [comment]
> Will require me to write an update, hopefully this weekend

[![PeepoHeart](https://cdn3.emoji.gg/emojis/2316-peepoheart.png)](https://emoji.gg/emoji/2316-peepoheart)
