### ISSUE TITLE
KTE Windows not visible

### ISSUE THREAD

**Issue by swissaviator** [typedeck0/Know-thy-enemy#24]
HI there, i got this Issue nearly months now and I thought "nah, let's just wait for the next version" but Since I got some calls from others that it works finde for them, I wanna ask here.

So my KTE Windows ist just not visible at all. I Do have the latest versions of Arc and KTE, The Log says "maybe? KTE NOT INIT" but I wasn't able to find out how to fix this.

I saw another Issue: https://github.com/typedeck0/Know-thy-enemy/issues/21
But I can't see any solution there. Would be great if you can help me out here.

**Comment by typedeck0** [comment]
I am just waiting for arcdps to update

**Comment by typedeck0** [comment]
Updated.

**Comment by swissaviator** [comment]
Still got the Issue after updating :(

**Comment by typedeck0** [comment]
> Still got the Issue after updating :(

make sure you are on the most recent arcdps from https://www.deltaconnected.com/arcdps/

![image](https://github.com/typedeck0/Know-thy-enemy/assets/113395677/fdad8cbe-5385-465d-9f3c-0c74d2679477)

**Comment by swissaviator** [comment]
I had the correct version, but it still did not work. But after the Game Update yesterday, the window was visible again! Thanks a lot =)
