### ISSUE TITLE
Can't display window

### ISSUE THREAD

**Issue by SerkanUnalan** [typedeck0/Know-thy-enemy#26]
Don't know how else to describe it, but the windows doesn't show at all. Dll is where it is supposed to be, but checking the tickbox under options/extensions/know thy enemy does nothing. Reset position button or reset setting button does not resolve the issue.

**Comment by typedeck0** [comment]
Did you update arcdps? The latest version of arcdps is 20240313-171038, the latest KTE is compatible with version 20240309-195905.

**Comment by SerkanUnalan** [comment]
Yes it always auto-updates, but I checked before 20240313 and after as well. I am not certain the version before 20240313 was 20240309 or not tho.

**Comment by SerkanUnalan** [comment]
Resolved - Fixed since last update.
