### ISSUE TITLE
Window not appearing for Extension

### ISSUE THREAD

**Issue by Andrewzz** [typedeck0/Know-thy-enemy#29]
Using the newest ArcDPS version, the extension appears on the ArcDPS configuration window, but the Extension window is not appearing. Is it a compatibility issue?

![image](https://github.com/user-attachments/assets/c640f25b-31b7-4d3d-aa73-5241ce655646)
![image](https://github.com/user-attachments/assets/96e5a681-9f00-417a-902f-1a7f3c24e72d)

**Comment by vvv850** [comment]
Same here. Started a week ago and couldn't make it work again.

**Comment by typedeck0** [comment]
this is due to version mismatch between arcdps and KTE, have to wait for KTE update
