### ISSUE TITLE
Please post any team ids here, not sure if repeated across servers

### ISSUE THREAD

**Issue by typedeck0** [typedeck0/Know-thy-enemy#3]
Please share team ids and colors:
2739: Green
432: Blue

**Comment by John-Dean** [comment]
This seems consistent with my testing

Green: 2739:
![image](https://user-images.githubusercontent.com/13804523/220633231-f10d3172-b848-41c3-9a3a-055deb584494.png)

**Comment by John-Dean** [comment]
Blue 432:
![image](https://user-images.githubusercontent.com/13804523/220634286-084b3420-eac3-44cb-80c7-0465a046a3d7.png)

**Comment by John-Dean** [comment]
![image](https://user-images.githubusercontent.com/13804523/221431914-8da62f52-8f98-4ee0-82c7-f053365d751a.png)
705 Red 
432 Blue

**Comment by typedeck0** [comment]
I'm going to guess and say that they are the same, maybe changes on relink?
