### ISSUE TITLE
Install location/arcdps extension integration

### ISSUE THREAD

**Issue by John-Dean** [typedeck0/Know-thy-enemy#4]
Hello,

Just a question from me, all my other arcdps plugins install in {GW2 Directory}/addons/arcdps/
![image](https://user-images.githubusercontent.com/13804523/220597635-50bbbd88-3502-400a-9950-ac26c1b4969a.png)

and I can see this is where the settings are kept (bottom .txt file)

These are also able to update automatically using the "automatically update extensions" checkbox:
![image](https://user-images.githubusercontent.com/13804523/220598323-477ebb4c-7be3-47b2-85a9-a424d16e9f7a.png)

Finally they appear in the "Extensions" tab along the top:
![image](https://user-images.githubusercontent.com/13804523/220598411-d9fad57d-ab43-4444-9bbd-292dbc0c4b11.png)

It would be great if this plugin was installed in the same install location (if possible) and had the same auto-update integration (which I believe is an arcdps feature?)

Thanks,
John

**Comment by typedeck0** [comment]
You can put the dll into the bin64 folder as well. Im not sure if the [DLL search order](https://learn.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-search-order) goes all the way to the addons/arcdps directory. 
As far as automatic updates, I don't like them and I will not be implementing it. Sorry. Once all the features are implemented I dont plan on needing to update.
I can move the toggle for kte to the extensions tab. It's probably better for future developments.

**Comment by typedeck0** [comment]
8752463 Added features, no auto-update
