### ISSUE TITLE
Background visibility

### ISSUE THREAD

**Issue by John-Dean** [typedeck0/Know-thy-enemy#5]
It would be great if this supported a style option when rightclicking the window:
![image](https://user-images.githubusercontent.com/13804523/220599001-f9c2d180-2f8d-45cb-b3a9-9bf9fcf10a21.png)

Personally my UI is all transparent:
![image](https://user-images.githubusercontent.com/13804523/220599085-06fb2410-795d-4c5f-98af-a72601737788.png)
![image](https://user-images.githubusercontent.com/13804523/220599097-cd57239c-ee31-4320-9edd-3b4bdedcdf00.png)

and this would be a big feature for me if possible.

Thanks,
John

**Comment by typedeck0** [comment]
8752463 title and background can now be transparent.
