### ISSUE TITLE
v2.0 crashing game

### ISSUE THREAD

**Issue by John-Dean** [typedeck0/Know-thy-enemy#6]
Hello,

Updated to v2.0 this morning and I've had 4 game crashes in <10m while in WvW. Had no issues before this. Would it be possible to enable/disable the WvW detection code via a checkbox?

It's also getting stuck on "Checking if WvW map..."  all the time for me (Tested on EBG with and without squad and on Desert BL)
![image](https://user-images.githubusercontent.com/13804523/220601601-4ddd69f4-bbd5-48f5-a325-2f5ab28e888a.png)

I am using the Steam client with `-provider Portal` flag if that's helpful?

John

**Comment by typedeck0** [comment]
I reverted the wvw map check in 2.1.
