### ISSUE TITLE
split view?

### ISSUE THREAD

**Issue by iruixos** [typedeck0/Know-thy-enemy#7]
hello! great extension

just wondering if it's possible to add a split view option instead of tabs so that i can see both colours at once? 

thanks :)

**Comment by typedeck0** [comment]
Shouldnt be too bad, ill play around a bit

**Comment by typedeck0** [comment]
https://github.com/typedeck0/Know-thy-enemy/commit/274766e9817b068a82d72ec4bfaf54f5137a446c
