### ISSUE TITLE
Can't resize window's stats

### ISSUE THREAD

**Issue by OnofrioAnnosciaApSystem** [typedeck0/Know-thy-enemy#8]
![image](https://github.com/typedeck0/Know-thy-enemy/assets/118355141/8282510a-383e-4bc2-b367-003cc341f8c6)

the windows not have the lower right corner for resize

is my bad?
i miss something?

**Comment by typedeck0** [comment]
if you have the arcdps modification keybinds set you have to hold those down to move and resize

if this is checked in arcdps you have to hold down the modifier key to move and rezise
![image](https://github.com/typedeck0/Know-thy-enemy/assets/113395677/a3225cb5-7c2c-4cfd-b829-4f37c9608abf)

![image](https://github.com/typedeck0/Know-thy-enemy/assets/113395677/cb176b90-151c-471c-bf8f-77e60a449110)

**Comment by typedeck0** [comment]
was this resolved?

**Comment by OnofrioAnnosciaApSystem** [comment]
yes but i have to set also modifier 2 to make it works
