### ISSUE TITLE
Thy My Enemy Not Working

### ISSUE THREAD

**Issue by ducadiebonhawke** [typedeck0/Know-thy-enemy#9]
Hello , Thy my enemy stop to work. 
It's disappeared and I do not see anymore .
It's regularly installed , see image 
<img width="296" alt="Immagine 2023-05-22 001728" src="https://github.com/typedeck0/Know-thy-enemy/assets/134237499/6d5b3f5e-0fb6-4b2c-b924-629db0661558">

**Comment by ducadiebonhawke** [comment]
To be precise do not work the latest release. 
For testing , I tried with the previous and it works

**Comment by typedeck0** [comment]
Try deleting the know_thy_enemy settings in the bin64/arcdps folder (the same folder as the arcdps settings, if there are two files there delete both)

**Comment by ducadiebonhawke** [comment]
I made it and I put the version 3.3 new downloaded in the folder bin 64 and it doesn't work , (previously it was in the GW2 folder), see image.
Than I moved out from bin64 and placed in the GW2 and doesn't work.
After I removed the version 3.3 installed the 3.2 in bin64 and works .
It looks the issue it is in the 3.3 
<img width="264" alt="Immagine 2023-05-22 084844" src="https://github.com/typedeck0/Know-thy-enemy/assets/134237499/dcbadaf9-6a46-4ca8-86f7-9bd0708c3394">

**Comment by Ariacell** [comment]
I was able to replicate this as well :). Version 3.3 in either Gw2.exe root or bin_64 did not appear to load in arcdps extensions. Reverting to release 3.2 in the bin_64 folder loaded correctly.

Unfortunately I can't seem to get the dll built from source to load for either release version, so I haven't been able to get much more detail. ~Can I confirm imgui [v1.89.4](https://github.com/ocornut/imgui/releases/tag/v1.89.4) is a supported version for building locally?~ I'm an idiot. Building commit tagged 3.2 from source with imgui 1.80 does in fact also load correctly from bin_64.

Edit: after some more testing I can no longer replicate this. @ducadiebonhawke maybe it was something related to upgrading? The only time I was able to replicate it was after my initial upgrade, immediately after replacing the 3.2 dll in my bin_64 folder with 3.3.

**Comment by typedeck0** [comment]
Ok it's more than likely a problem with getting the map ID from arcdps, will look in to it today

**Comment by ducadiebonhawke** [comment]
It worked until yesterdy around 22,00 CEST , than off


Inviato da Yahoo Mail per iPhone


Il lunedì, maggio 22, 2023, 2:47 PM, typedeck0 ***@***.***> ha scritto:




Ok it's more than likely a problem with getting the map ID from arcdps, will look in to it today

**Comment by typedeck0** [comment]
Yeah unfortunately I can not reproduce this problem, try deleting these know_thy_enemy files in the "Guild Wars 2\addons\arcdps" folder. And also make sure you are on a WvW Map or Armistice Bastion (Edge of the Mists is disabled)

![image](https://github.com/typedeck0/Know-thy-enemy/assets/113395677/b3d0f3c9-5483-48bd-94e6-1dec135fe011)

**Comment by ducadiebonhawke** [comment]
Have you checked if it works now ?Il giorno 22 mag 2023, alle ore 14:47, typedeck0 ***@***.***> ha scritto:﻿
Ok it's more than likely a problem with getting the map ID from arcdps, will look in to it today

**Comment by typedeck0** [comment]
> Have you checked if it works now ?Il giorno 22 mag 2023, alle ore 14:47, typedeck0 ***@***.***> ha scritto:﻿ Ok it's more than likely a problem with getting the map ID from arcdps, will look in to it today —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

Check my comment above.

**Comment by ducadiebonhawke** [comment]
Hello , I could try today . I made what you suggested above and it works now.
